### ISSUE TITLE
Use "address" not "device_address" for specifying the I2C address, for consistency with other drivers

### ISSUE THREAD

**Issue by deshipu** [adafruit/Adafruit_CircuitPython_MCP9808#12]
We need a consistent API between different drivers, and all I2C-based drivers should use the same keywords.

**Comment by tannewt** [comment]
I'd rather move to `device_address` so it doesn't get confused with memory address.

**Comment by deshipu** [comment]
Well, that would involve changing a lot of code out there. And I think the context is pretty clear here.

**Comment by tannewt** [comment]
Ok, `address` is fine.
