### ISSUE TITLE
Example for devices on different address

### ISSUE THREAD

**Issue by signalmeister** [adafruit/Adafruit_CircuitPython_MCP9808#19]
The examples provided and the documentation given do not have any information about reading a device set to other than the default address.

The Adafruit MCP9808 Library Documentation [https://buildmedia.readthedocs.org/media/pdf/adafruit-circuitpython-mcp9808/latest/adafruit-circuitpython-mcp9808.pdf] defines the interface as
**class adafruit_mcp9808.MCP9808(i2c_bus,address=24)**? Is it possible to include a line in the example code to show this without the reader needing to resort to trawling for the library definitions?

**Comment by ladyada** [comment]
hiya - please submit an update to the example code as a PR and we'll take a look at it :)

**Comment by signalmeister** [comment]
I have created a pull [request](https://github.com/signalmeister/Adafruit_CircuitPython_MCP9808/pull/1) (which is what I think you meant). I am new to this so please let me know if I have not done it correctly.

**Comment by signalmeister** [comment]
Hopefully I have done this in the right way now - after some advice about getting confused with which branches to do it against.

**Comment by signalmeister** [comment]
Being new to this, I am not sure what the next step is. I submitted the PR and there was a comment about it not satisfying a particular check. I have tried to address that in the following  https://github.com/adafruit/Adafruit_CircuitPython_MCP9808/pull/20/commits/1caf93f7ab09c4d9a9f04a9eaca8779f8e3084c6

Can anyone advise me what now needs to be done?

**Comment by ladyada** [comment]
the error is
```
************* Module mcp9808_simpletest

C: 11, 0: Line too long (125/100) (line-too-long)
```
split up that line so it is not as long

**Comment by signalmeister** [comment]
OK. I'll have a go. 

So that I know for next time, how would I find that out for myself? Is
there some sort of tutorial about this process? 

On 2019-10-03 18:15, ladyada wrote:

> the error is
> 
> ************* Module mcp9808_simpletest
> 
> C: 11, 0: Line too long (125/100) (line-too-long)
> 
> split up that line so it is not as long 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/adafruit/Adafruit_CircuitPython_MCP9808/issues/19?email_source=notifications&amp;email_token=AK5IOOC7JDGUTI7LLH73U6DQMYSD5A5CNFSM4IYYSGBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAI5KOY#issuecomment-538039611
[2]

**Comment by ladyada** [comment]
yes https://learn.adafruit.com/improve-your-code-with-pylint

**Comment by signalmeister** [comment]
Thanks.
